development:
  adapter: mysql2
  encoding: utf8
  database: ristoran8_development
  username: ristoran8
  password: ristoran8
  collation: utf8_general_ci
  host: localhost
  port: 3306
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: ristoran8_test
  username: ristoran8
  password: ristoran8
  collation: utf8_general_ci
  host: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: ristoran8
  username: ristoran8
  password: ristoran8
  collation: utf8_general_ci
  host: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock
  pool: 5
